name: CI-cd

on:
  push:
    branches: ["01_workflows"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      - name: Unzip data file
        run: |
          mkdir -p data
          unzip -o data/Metro_Nashville_Police_Department_Incidents.zip -d data

      - name: Run plot.py
        run: python plot.py

      - run: echo "Executar o docker build"
      - run: echo "Enviar a imagem Docker para o Docker hub"

  CD:     
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "Configurar o kubeconfig"
