name: CI with Commit Image | Artifact

on:
  push:
    branches: ["01_ex_03_Plotting_chicken_locations"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        # pandas matplotlib

      - name: Unzip data file
        run: |
          mkdir -p data
          unzip -o data/Metro_Nashville_Police_Department_Incidents.zip -d data

      - name: Download Natural Earth Admin 0 Countries shapefile
        run: |
          mkdir -p data/maps
          wget -O data/maps/ne_110m_admin_0_countries.zip "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
          unzip -o data/maps/ne_110m_admin_0_countries.zip -d data/maps

      - name: Run plot.py
        env:
          RUN_DATE: ${{ github.run_started_at }}
          RUN_NUMBER: ${{ github.run_number }}
        run: python plot.py

      - name: Commit and push generated image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add img/
          git commit -m "Add generated plot image [skip ci]" || echo "No changes to commit"
          git push
