name: CI-cd

on:
 push:
    branches: ["main"]

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code (1st step)
              uses: actions/checkout@v2
            - name: Set up Python (2rd step)
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            - name: Install dependencies (3rd step)
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt 
            - name: Run tests
              run: |
                python -m unittest discover -s tests -p "*.py"
            - name: Run plot script (4th step)
              run: |
                python plot.py
            - name: Upload plot image
              uses: actions/upload-artifact@v2
              with:
                name: school_locations_plot

            - name: Build Docker image
            - run: echo "Obter o código"
            - run: echo "Executar o docker build"
            - run: echo "Enviar a imagem Docker para o Docker hub"
    CD:     
        needs: [CI]
        runs-on: ubuntu-latest
        steps:
            - run: echo "Obter codigo"
            - run: echo "Configurar o kubeconfig"
